# Generated by Django 3.0 on 2019-12-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contentimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
